version: 2

models:
  - name: customer_address
    columns: 
      - name: name
        tests:
          - unique
          - not_null
    columns: 
      - name: email
        tests:
          - unique
          - not_null
    columns: 
      - name: address
        tests:
          - unique
          - not_null
          